### ISSUE TITLE
Chart.js problème avec les bulles

### ISSUE THREAD

**Issue by KumR67** [Samuel-Scalbert/SOFTware-Viz#6]
Graphique : quand 2 types de mentions sont à la même date et de même quantité, on ne voit qu'une pastille d'une couleur

**Comment by Samuel-Scalbert** [comment]
fixed in 2e5e44e3cbf8434be0a282b163646a784a87c7f6

Le correctif est assez complexe : avant la génération des bulles, on vérifie les bulles superposées, puis on modifie les dates pour les déplacer sur le graphique. Ensuite, pour afficher le nombre de mentions, on crée un dataset et une bulle invisible et non cliquable.
